/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
var __export = (target, all) => {
  __markAsModule(target);
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __reExport = (target, module2, desc) => {
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && key !== "default")
        __defProp(target, key, { get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable });
  }
  return target;
};
var __toModule = (module2) => {
  return __reExport(__markAsModule(__defProp(module2 != null ? __create(__getProtoOf(module2)) : {}, "default", module2 && module2.__esModule && "default" in module2 ? { get: () => module2.default, enumerable: true } : { value: module2, enumerable: true })), module2);
};

// main.ts
__export(exports, {
  default: () => XPublisherPlugin
});
var import_obsidian = __toModule(require("obsidian"));
var path = __toModule(require("path"));
var DEFAULT_SETTINGS = {
  serverUrl: "http://127.0.0.1:3001",
  clientId: "",
  clientSecret: "",
  headlessMode: true,
  openAfterPublish: true,
  showNotification: true
};
async function updateFrontmatter(app, file, updates) {
  const content = await app.vault.read(file);
  const frontmatterRegex = /^---\s*\n([\s\S]*?)\n---\s*\n?/;
  const match = content.match(frontmatterRegex);
  let newContent;
  if (match) {
    const frontmatterStr = match[1];
    const frontmatterLines = frontmatterStr.split("\n");
    const frontmatterObj = {};
    for (const line of frontmatterLines) {
      const colonIndex = line.indexOf(":");
      if (colonIndex > 0) {
        const key = line.substring(0, colonIndex).trim();
        let value = line.substring(colonIndex + 1).trim();
        if (value.startsWith('"') && value.endsWith('"') || value.startsWith("'") && value.endsWith("'")) {
          value = value.slice(1, -1);
        }
        frontmatterObj[key] = value;
      }
    }
    for (const [key, value] of Object.entries(updates)) {
      if (value === null || value === void 0) {
        delete frontmatterObj[key];
      } else {
        frontmatterObj[key] = value;
      }
    }
    const newFrontmatterLines = [];
    for (const [key, value] of Object.entries(frontmatterObj)) {
      if (value === "" || value === null || value === void 0) {
        newFrontmatterLines.push(`${key}: ""`);
      } else if (typeof value === "string" && (value.includes(":") || value.includes("#") || value.includes('"'))) {
        newFrontmatterLines.push(`${key}: "${value.replace(/"/g, '\\"')}"`);
      } else {
        newFrontmatterLines.push(`${key}: ${value}`);
      }
    }
    const newFrontmatter = `---
${newFrontmatterLines.join("\n")}
---
`;
    newContent = content.replace(frontmatterRegex, newFrontmatter);
  } else {
    const newFrontmatterLines = [];
    for (const [key, value] of Object.entries(updates)) {
      if (value !== null && value !== void 0) {
        if (value === "") {
          newFrontmatterLines.push(`${key}: ""`);
        } else if (typeof value === "string" && (value.includes(":") || value.includes("#") || value.includes('"'))) {
          newFrontmatterLines.push(`${key}: "${value.replace(/"/g, '\\"')}"`);
        } else {
          newFrontmatterLines.push(`${key}: ${value}`);
        }
      }
    }
    const newFrontmatter = `---
${newFrontmatterLines.join("\n")}
---

`;
    newContent = newFrontmatter + content;
  }
  await app.vault.modify(file, newContent);
}
function getTodayDate() {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, "0");
  const day = String(now.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}
var XPublisherClient = class {
  constructor(serverUrl) {
    this.serverUrl = serverUrl.replace(/\/$/, "");
  }
  setServerUrl(url) {
    this.serverUrl = url.replace(/\/$/, "");
  }
  async healthCheck() {
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: `${this.serverUrl}/health`,
        method: "GET"
      });
      return response.status === 200;
    } catch (e) {
      return false;
    }
  }
  async startOAuth(clientId, clientSecret) {
    const body = { clientId };
    if (clientSecret)
      body.clientSecret = clientSecret;
    const response = await (0, import_obsidian.requestUrl)({
      url: `${this.serverUrl}/oauth/start`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
      throw: false
    });
    if (response.status === 409)
      return;
    if (response.status !== 200) {
      const parsed = JSON.parse(response.text);
      throw new Error(parsed.error || `HTTP ${response.status}`);
    }
  }
  async getOAuthStatus() {
    var _a, _b;
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: `${this.serverUrl}/oauth/status`,
        method: "GET",
        throw: false
      });
      if (response.status !== 200) {
        return { status: "error", error: "\u30B5\u30FC\u30D0\u30FC\u3092\u518D\u8D77\u52D5\u3057\u3066\u304F\u3060\u3055\u3044\uFF08npm run server\uFF09", authenticated: false };
      }
      const text = (_b = (_a = response.text) == null ? void 0 : _a.trim()) != null ? _b : "";
      if (!text.startsWith("{")) {
        return { status: "error", error: "\u30B5\u30FC\u30D0\u30FC\u3092\u518D\u8D77\u52D5\u3057\u3066\u304F\u3060\u3055\u3044\uFF08npm run server\uFF09", authenticated: false };
      }
      return JSON.parse(text);
    } catch (e) {
      return { status: "error", error: "\u30B5\u30FC\u30D0\u30FC\u304C\u8D77\u52D5\u3057\u3066\u3044\u307E\u305B\u3093\uFF08npm run server\uFF09", authenticated: false };
    }
  }
  async saveSessionCookies(authToken, csrfToken) {
    const body = { authToken };
    if (csrfToken)
      body.csrfToken = csrfToken;
    const response = await (0, import_obsidian.requestUrl)({
      url: `${this.serverUrl}/session/cookies`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
      throw: false
    });
    if (response.status !== 200) {
      const parsed = JSON.parse(response.text);
      throw new Error(parsed.error || `HTTP ${response.status}`);
    }
  }
  async publish(params) {
    try {
      const bodyStr = JSON.stringify({
        title: params.title,
        markdown: params.markdown,
        images: params.images || [],
        headless: params.headless !== false
      });
      const response = await (0, import_obsidian.requestUrl)({
        url: `${this.serverUrl}/publish`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: bodyStr,
        throw: false
      });
      if (response.status !== 200) {
        const body = JSON.parse(response.text);
        throw new Error(body.error || `HTTP ${response.status}`);
      }
      const result = JSON.parse(response.text);
      return { success: true, articleUrl: result.articleUrl };
    } catch (error) {
      return { success: false, error: error.message || "Unknown error" };
    }
  }
};
async function parseNote(app, file) {
  const content = await app.vault.read(file);
  const cache = app.metadataCache.getFileCache(file);
  const title = extractTitle(content, file, cache);
  const body = prepareBody(content);
  const images = await extractImages(app, content, file);
  return { title, body, images };
}
function extractTitle(content, file, cache) {
  const frontmatter = cache == null ? void 0 : cache.frontmatter;
  if (frontmatter == null ? void 0 : frontmatter.title)
    return String(frontmatter.title);
  const h1Match = content.match(/^#\s+(.+)$/m);
  if (h1Match)
    return h1Match[1].trim();
  return file.basename;
}
function prepareBody(content) {
  return content.replace(/^---\s*\n[\s\S]*?\n---\s*\n?/, "").trim();
}
async function extractImages(app, content, file) {
  var _a;
  const images = [];
  const fileDir = ((_a = file.parent) == null ? void 0 : _a.path) || "";
  const vaultPath = app.vault.adapter.basePath || "";
  const obsidianRegex = /!\[\[([^\]|]+)(?:\|[^\]]+)?\]\]/g;
  let match;
  while ((match = obsidianRegex.exec(content)) !== null) {
    const info = resolveImageFile(app, match[1].trim(), fileDir, vaultPath);
    if (info)
      images.push(info);
  }
  const mdRegex = /!\[([^\]]*)\]\(([^)]+)\)/g;
  while ((match = mdRegex.exec(content)) !== null) {
    const srcPath = match[2].trim();
    if (srcPath.startsWith("http://") || srcPath.startsWith("https://"))
      continue;
    const info = resolveImageFile(app, srcPath, fileDir, vaultPath);
    if (info)
      images.push(info);
  }
  return images;
}
function resolveImageFile(app, imagePath, baseDir, vaultPath) {
  const fileName = path.basename(imagePath);
  const linkedFile = app.metadataCache.getFirstLinkpathDest(imagePath, baseDir);
  if (linkedFile && linkedFile instanceof import_obsidian.TFile) {
    const absolutePath = vaultPath ? `${vaultPath}/${linkedFile.path}` : linkedFile.path;
    return { fileName, absolutePath, exists: true };
  }
  const directFile = app.vault.getAbstractFileByPath(imagePath);
  if (directFile && directFile instanceof import_obsidian.TFile) {
    const absolutePath = vaultPath ? `${vaultPath}/${directFile.path}` : directFile.path;
    return { fileName, absolutePath, exists: true };
  }
  return { fileName, absolutePath: "", exists: false };
}
var PublishConfirmModal = class extends import_obsidian.Modal {
  constructor(app, parsedNote, onConfirm, onCancel) {
    super(app);
    this.parsedNote = parsedNote;
    this.onConfirm = onConfirm;
    this.onCancel = onCancel;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "X Article \u306B\u6295\u7A3F" });
    new import_obsidian.Setting(contentEl).setName("\u30BF\u30A4\u30C8\u30EB").setDesc(this.parsedNote.title);
    const images = this.parsedNote.images;
    if (images.length > 0) {
      const found = images.filter((i) => i.exists);
      const missing = images.filter((i) => !i.exists);
      new import_obsidian.Setting(contentEl).setName(`\u753B\u50CF (${images.length}\u4EF6)`).setDesc(found.map((i) => `\u2713 ${i.fileName}`).join(", ") + (missing.length > 0 ? `  \u2717 ${missing.map((i) => i.fileName).join(", ")}` : ""));
    }
    const preview = this.parsedNote.body.substring(0, 200);
    new import_obsidian.Setting(contentEl).setName("\u672C\u6587\u30D7\u30EC\u30D3\u30E5\u30FC").setDesc(preview + (this.parsedNote.body.length > 200 ? "..." : ""));
    const btnContainer = contentEl.createDiv();
    btnContainer.style.cssText = "display: flex; gap: 8px; justify-content: flex-end; margin-top: 16px;";
    const cancelBtn = btnContainer.createEl("button", { text: "\u30AD\u30E3\u30F3\u30BB\u30EB" });
    cancelBtn.addEventListener("click", () => {
      this.close();
      this.onCancel();
    });
    const confirmBtn = btnContainer.createEl("button", {
      text: "X Article \u306B\u6295\u7A3F",
      cls: "mod-cta"
    });
    confirmBtn.addEventListener("click", () => {
      this.close();
      this.onConfirm();
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var XPublisherSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.pollingActive = false;
    this.plugin = plugin;
  }
  display() {
    this.pollingActive = false;
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "X Article Publisher \u8A2D\u5B9A" });
    containerEl.createEl("h3", { text: "X Developer App" });
    const descEl = containerEl.createEl("p", { cls: "setting-item-description" });
    descEl.style.cssText = "margin: 0 0 12px; font-size: 13px; color: var(--text-muted);";
    descEl.innerHTML = '<a href="https://developer.x.com" target="_blank">developer.x.com</a> \u3067\u30A2\u30D7\u30EA\u3092\u4F5C\u6210\u3057\u3001OAuth 2.0 \u3092\u6709\u52B9\u5316\u3002Callback URI \u306B <code>http://127.0.0.1:3001/oauth/callback</code> \u3092\u767B\u9332\u3057\u3066\u304F\u3060\u3055\u3044\u3002';
    new import_obsidian.Setting(containerEl).setName("Client ID").setDesc("X Developer Portal \u2192 Keys and tokens \u2192 Client ID").addText((text) => text.setPlaceholder("\u4F8B: xxxxxxxxxxxxxxxxxxxx").setValue(this.plugin.settings.clientId).onChange(async (value) => {
      this.plugin.settings = { ...this.plugin.settings, clientId: value };
      await this.plugin.saveSettings();
    }));
    let secretInputEl;
    new import_obsidian.Setting(containerEl).setName("Client Secret").setDesc("Confidential Client \u306E\u5834\u5408\u306E\u307F\u5165\u529B\uFF08Public Client \u306F\u7A7A\u6B04\u3067 OK\uFF09").addText((text) => {
      text.inputEl.type = "password";
      secretInputEl = text.inputEl;
      text.setPlaceholder("Client Secret\uFF08\u4EFB\u610F\uFF09").setValue(this.plugin.settings.clientSecret).onChange(async (value) => {
        this.plugin.settings = { ...this.plugin.settings, clientSecret: value };
        await this.plugin.saveSettings();
      });
    }).addExtraButton((button) => {
      button.setIcon("eye").setTooltip("\u8868\u793A/\u975E\u8868\u793A").onClick(() => {
        const hidden = secretInputEl.type === "password";
        secretInputEl.type = hidden ? "text" : "password";
        button.setIcon(hidden ? "eye-off" : "eye");
      });
    });
    containerEl.createEl("h3", { text: "X \u30A2\u30AB\u30A6\u30F3\u30C8\u9023\u643A" });
    const statusEl = containerEl.createDiv();
    statusEl.style.cssText = "padding: 4px 0 12px; font-size: 13px;";
    statusEl.setText("\u25CF \u63A5\u7D9A\u72B6\u614B\u3092\u78BA\u8A8D\u4E2D...");
    let connectBtn;
    new import_obsidian.Setting(containerEl).setName("X \u30A2\u30AB\u30A6\u30F3\u30C8\u3092\u9023\u643A").setDesc("\u30AF\u30EA\u30C3\u30AF\u3059\u308B\u3068\u30D6\u30E9\u30A6\u30B6\u304C\u8D77\u52D5\u3057\u3001X \u306E\u30ED\u30B0\u30A4\u30F3\u753B\u9762\u304C\u8868\u793A\u3055\u308C\u307E\u3059").addButton((button) => {
      connectBtn = button;
      button.setButtonText("\u9023\u643A\u3059\u308B").setCta().onClick(() => this.startOAuthFlow(connectBtn, statusEl));
    });
    containerEl.createEl("h3", { text: "\u30BB\u30C3\u30B7\u30E7\u30F3 Cookie \u8A2D\u5B9A" });
    const cookieDescEl = containerEl.createEl("p", { cls: "setting-item-description" });
    cookieDescEl.style.cssText = "margin: 0 0 12px; font-size: 13px; color: var(--text-muted);";
    cookieDescEl.innerHTML = '<b>\u8A2D\u5B9A\u65B9\u6CD5\uFF1A</b> Safari / Chrome \u3067 <a href="https://x.com" target="_blank">x.com</a> \u306B\u30ED\u30B0\u30A4\u30F3\u3057\u305F\u72B6\u614B\u3067\u3001<br>\u958B\u767A\u8005\u30C4\u30FC\u30EB\uFF08Mac: <code>Cmd+Option+I</code> / Win: <code>F12</code>\uFF09\u3092\u958B\u304D\u3001<br><b>Application</b> \u30BF\u30D6 \u2192 <b>Cookies</b> \u2192 <b>.x.com</b> \u3092\u9078\u629E\u3057\u3001<br><code>auth_token</code> \u3068 <code>ct0</code> \u306E Value \u3092\u30B3\u30D4\u30FC\u3057\u3066\u8CBC\u308A\u4ED8\u3051\u3066\u304F\u3060\u3055\u3044\u3002';
    let authTokenInputEl;
    new import_obsidian.Setting(containerEl).setName("auth_token").setDesc("X \u306E\u30BB\u30C3\u30B7\u30E7\u30F3\u8A8D\u8A3C\u30C8\u30FC\u30AF\u30F3\uFF08\u5FC5\u9808\uFF09").addText((text) => {
      text.inputEl.type = "password";
      authTokenInputEl = text.inputEl;
      text.setPlaceholder("auth_token \u306E\u5024\u3092\u8CBC\u308A\u4ED8\u3051");
    }).addExtraButton((button) => {
      button.setIcon("eye").setTooltip("\u8868\u793A/\u975E\u8868\u793A").onClick(() => {
        const hidden = authTokenInputEl.type === "password";
        authTokenInputEl.type = hidden ? "text" : "password";
        button.setIcon(hidden ? "eye-off" : "eye");
      });
    });
    let ct0InputEl;
    new import_obsidian.Setting(containerEl).setName("ct0 (CSRF Token)").setDesc("CSRF \u30C8\u30FC\u30AF\u30F3\uFF08\u63A8\u5968\uFF09").addText((text) => {
      text.inputEl.type = "password";
      ct0InputEl = text.inputEl;
      text.setPlaceholder("ct0 \u306E\u5024\u3092\u8CBC\u308A\u4ED8\u3051");
    }).addExtraButton((button) => {
      button.setIcon("eye").setTooltip("\u8868\u793A/\u975E\u8868\u793A").onClick(() => {
        const hidden = ct0InputEl.type === "password";
        ct0InputEl.type = hidden ? "text" : "password";
        button.setIcon(hidden ? "eye-off" : "eye");
      });
    });
    const sessionStatusEl = containerEl.createDiv();
    sessionStatusEl.style.cssText = "padding: 4px 0 12px; font-size: 13px;";
    sessionStatusEl.setText("\u25CF \u72B6\u614B\u3092\u78BA\u8A8D\u4E2D...");
    new import_obsidian.Setting(containerEl).setName("Cookie \u3092\u4FDD\u5B58").setDesc("\u5165\u529B\u3057\u305F Cookie \u3092\u30B5\u30FC\u30D0\u30FC\u306B\u9001\u4FE1\u3057\u307E\u3059").addButton((button) => {
      button.setButtonText("\u4FDD\u5B58\u3059\u308B").setCta().onClick(async () => {
        const authToken = authTokenInputEl.value.trim();
        const ct0 = ct0InputEl.value.trim();
        if (!authToken) {
          new import_obsidian.Notice("auth_token \u3092\u5165\u529B\u3057\u3066\u304F\u3060\u3055\u3044");
          return;
        }
        button.setButtonText("\u4FDD\u5B58\u4E2D...").setDisabled(true);
        try {
          await this.plugin.xClient.saveSessionCookies(authToken, ct0 || void 0);
          sessionStatusEl.setText("\u25CF Cookie \u8A2D\u5B9A\u6E08\u307F \u2705\uFF08\u6295\u7A3F\u53EF\u80FD\uFF09");
          sessionStatusEl.style.color = "#10b981";
          authTokenInputEl.value = "";
          ct0InputEl.value = "";
          new import_obsidian.Notice("Cookie \u3092\u4FDD\u5B58\u3057\u307E\u3057\u305F\uFF01\u6295\u7A3F\u3067\u304D\u308B\u3088\u3046\u306B\u306A\u308A\u307E\u3057\u305F\u3002");
        } catch (err) {
          sessionStatusEl.setText(`\u25CF \u30A8\u30E9\u30FC: ${err.message}`);
          sessionStatusEl.style.color = "#ef4444";
          new import_obsidian.Notice(`Cookie \u306E\u4FDD\u5B58\u306B\u5931\u6557\u3057\u307E\u3057\u305F: ${err.message}`);
        } finally {
          button.setButtonText("\u4FDD\u5B58\u3059\u308B").setDisabled(false);
        }
      });
    });
    this.checkInitialStatus(statusEl, connectBtn, sessionStatusEl);
    containerEl.createEl("h3", { text: "\u52D5\u4F5C\u8A2D\u5B9A" });
    new import_obsidian.Setting(containerEl).setName("\u30D8\u30C3\u30C9\u30EC\u30B9\u30E2\u30FC\u30C9").setDesc("\u8A18\u4E8B\u6295\u7A3F\u6642\u306B\u30D6\u30E9\u30A6\u30B6\u3092\u975E\u8868\u793A\u3067\u5B9F\u884C\uFF08\u63A8\u5968: ON\uFF09").addToggle((toggle) => toggle.setValue(this.plugin.settings.headlessMode).onChange(async (value) => {
      this.plugin.settings = { ...this.plugin.settings, headlessMode: value };
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u6295\u7A3F\u5F8C\u306B X.com \u3092\u958B\u304F").setDesc("\u6295\u7A3F\u5F8C\u306B\u30D6\u30E9\u30A6\u30B6\u3067 X Articles \u3092\u958B\u304F").addToggle((toggle) => toggle.setValue(this.plugin.settings.openAfterPublish).onChange(async (value) => {
      this.plugin.settings = { ...this.plugin.settings, openAfterPublish: value };
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u901A\u77E5\u3092\u8868\u793A").setDesc("\u6210\u529F\u30FB\u30A8\u30E9\u30FC\u6642\u306B\u30DD\u30C3\u30D7\u30A2\u30C3\u30D7\u901A\u77E5\u3092\u8868\u793A").addToggle((toggle) => toggle.setValue(this.plugin.settings.showNotification).onChange(async (value) => {
      this.plugin.settings = { ...this.plugin.settings, showNotification: value };
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "\u8A73\u7D30\u8A2D\u5B9A" });
    new import_obsidian.Setting(containerEl).setName("\u30B5\u30FC\u30D0\u30FC URL").setDesc("\u30ED\u30FC\u30AB\u30EB HTTP \u30B5\u30FC\u30D0\u30FC\u306E URL\uFF08\u30C7\u30D5\u30A9\u30EB\u30C8: http://127.0.0.1:3001\uFF09").addText((text) => text.setPlaceholder(DEFAULT_SETTINGS.serverUrl).setValue(this.plugin.settings.serverUrl).onChange(async (value) => {
      this.plugin.settings = { ...this.plugin.settings, serverUrl: value || DEFAULT_SETTINGS.serverUrl };
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u30B5\u30FC\u30D0\u30FC\u63A5\u7D9A\u30C6\u30B9\u30C8").setDesc("\u30ED\u30FC\u30AB\u30EB\u30B5\u30FC\u30D0\u30FC\u3068\u306E\u63A5\u7D9A\u3092\u78BA\u8A8D").addButton((button) => button.setButtonText("\u30C6\u30B9\u30C8").onClick(async () => {
      button.setButtonText("\u78BA\u8A8D\u4E2D...");
      button.setDisabled(true);
      const ok = await this.plugin.xClient.healthCheck();
      button.setButtonText(ok ? "\u63A5\u7D9A\u6210\u529F \u2705" : "\u63A5\u7D9A\u5931\u6557 \u274C");
      setTimeout(() => {
        button.setButtonText("\u30C6\u30B9\u30C8");
        button.setDisabled(false);
      }, 2e3);
    }));
  }
  async checkInitialStatus(statusEl, btn, sessionStatusEl) {
    try {
      const status = await this.plugin.xClient.getOAuthStatus();
      this.applyStatusStyle(statusEl, status);
      this.applySessionStyle(sessionStatusEl, status);
      if (status.oauthConnected) {
        btn.setButtonText("\u518D\u9023\u643A");
      }
    } catch (e) {
      statusEl.setText("\u25CF \u30B5\u30FC\u30D0\u30FC\u306B\u63A5\u7D9A\u3067\u304D\u307E\u305B\u3093");
      statusEl.style.color = "var(--text-muted)";
      sessionStatusEl.setText("\u25CF \u30B5\u30FC\u30D0\u30FC\u306B\u63A5\u7D9A\u3067\u304D\u307E\u305B\u3093");
      sessionStatusEl.style.color = "var(--text-muted)";
    }
  }
  applyStatusStyle(statusEl, status) {
    if (status.oauthConnected) {
      statusEl.setText("\u25CF Bearer \u30C8\u30FC\u30AF\u30F3\u53D6\u5F97\u6E08\u307F");
      statusEl.style.color = "#10b981";
    } else if (status.status === "error" && status.error) {
      statusEl.setText(`\u25CF \u30A8\u30E9\u30FC: ${status.error}`);
      statusEl.style.color = "#ef4444";
    } else if (status.status === "pending") {
      statusEl.setText("\u25CF \u30D6\u30E9\u30A6\u30B6\u3067\u30ED\u30B0\u30A4\u30F3\u5F85\u6A5F\u4E2D...");
      statusEl.style.color = "#f59e0b";
    } else {
      statusEl.setText("\u25CF \u672A\u63A5\u7D9A");
      statusEl.style.color = "var(--text-muted)";
    }
  }
  applySessionStyle(sessionStatusEl, status) {
    if (status.sessionReady) {
      sessionStatusEl.setText("\u25CF Cookie \u8A2D\u5B9A\u6E08\u307F \u2705\uFF08\u6295\u7A3F\u53EF\u80FD\uFF09");
      sessionStatusEl.style.color = "#10b981";
    } else {
      sessionStatusEl.setText("\u25CF \u672A\u8A2D\u5B9A\uFF08auth_token \u3092\u5165\u529B\u3057\u3066\u304F\u3060\u3055\u3044\uFF09");
      sessionStatusEl.style.color = "var(--text-muted)";
    }
  }
  async startOAuthFlow(button, statusEl) {
    const { clientId, clientSecret } = this.plugin.settings;
    if (!clientId) {
      new import_obsidian.Notice("Client ID \u3092\u5165\u529B\u3057\u3066\u304F\u3060\u3055\u3044");
      return;
    }
    const isServerUp = await this.plugin.xClient.healthCheck();
    if (!isServerUp) {
      new import_obsidian.Notice("\u30B5\u30FC\u30D0\u30FC\u304C\u8D77\u52D5\u3057\u3066\u3044\u307E\u305B\u3093\u3002\u30BF\u30FC\u30DF\u30CA\u30EB\u3067 npm run server \u3092\u5B9F\u884C\u3057\u3066\u304F\u3060\u3055\u3044\u3002", 8e3);
      return;
    }
    button.setButtonText("\u8A8D\u8A3C\u4E2D...").setDisabled(true);
    statusEl.setText("\u25CF \u30D6\u30E9\u30A6\u30B6\u3067\u30ED\u30B0\u30A4\u30F3\u3057\u3066\u304F\u3060\u3055\u3044...");
    statusEl.style.color = "#f59e0b";
    try {
      await this.plugin.xClient.startOAuth(clientId, clientSecret || void 0);
    } catch (err) {
      button.setButtonText("\u9023\u643A\u3059\u308B").setDisabled(false);
      statusEl.setText(`\u25CF \u30A8\u30E9\u30FC: ${err.message}`);
      statusEl.style.color = "#ef4444";
      return;
    }
    this.pollingActive = true;
    await this.pollUntilComplete(button, statusEl);
  }
  async pollUntilComplete(button, statusEl) {
    const MAX_POLLS = 150;
    let count = 0;
    while (this.pollingActive && count < MAX_POLLS) {
      await new Promise((resolve) => setTimeout(resolve, 2e3));
      if (!this.pollingActive)
        break;
      count++;
      const status = await this.plugin.xClient.getOAuthStatus();
      if (status.oauthConnected || status.status === "success") {
        this.pollingActive = false;
        button.setButtonText("\u518D\u9023\u643A").setDisabled(false);
        statusEl.setText("\u25CF Bearer \u30C8\u30FC\u30AF\u30F3\u53D6\u5F97\u6E08\u307F");
        statusEl.style.color = "#10b981";
        if (status.sessionReady) {
          new import_obsidian.Notice("\u8A8D\u8A3C\u5B8C\u4E86\uFF01\u6295\u7A3F\u3067\u304D\u308B\u3088\u3046\u306B\u306A\u308A\u307E\u3057\u305F\u3002", 5e3);
        } else {
          new import_obsidian.Notice("OAuth \u5B8C\u4E86\u3002Cookie \u304C\u81EA\u52D5\u53D6\u5F97\u3067\u304D\u306A\u304B\u3063\u305F\u5834\u5408\u306F\u300C\u30BB\u30C3\u30B7\u30E7\u30F3 Cookie \u8A2D\u5B9A\u300D\u3067\u624B\u52D5\u5165\u529B\u3057\u3066\u304F\u3060\u3055\u3044\u3002", 1e4);
        }
        return;
      }
      if (status.status === "error") {
        this.pollingActive = false;
        button.setButtonText("\u9023\u643A\u3059\u308B").setDisabled(false);
        statusEl.setText(`\u25CF \u30A8\u30E9\u30FC: ${status.error || "\u4E0D\u660E\u306A\u30A8\u30E9\u30FC"}`);
        statusEl.style.color = "#ef4444";
        return;
      }
    }
    if (this.pollingActive) {
      this.pollingActive = false;
      button.setButtonText("\u9023\u643A\u3059\u308B").setDisabled(false);
      statusEl.setText("\u25CF \u30BF\u30A4\u30E0\u30A2\u30A6\u30C8\uFF08\u518D\u8A66\u884C\u3057\u3066\u304F\u3060\u3055\u3044\uFF09");
      statusEl.style.color = "#ef4444";
    }
  }
};
var XPublisherPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.xClient = new XPublisherClient(this.settings.serverUrl);
    this.addCommand({
      id: "publish-to-x-article",
      name: "X Article \u306B\u6295\u7A3F",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (file && file.extension === "md") {
          if (!checking)
            this.publishCurrentFile(file);
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "publish-to-x-article-quick",
      name: "X Article \u306B\u6295\u7A3F (\u78BA\u8A8D\u306A\u3057)",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (file && file.extension === "md") {
          if (!checking)
            this.publishCurrentFile(file, true);
          return true;
        }
        return false;
      }
    });
    this.addRibbonIcon("upload", "X Article \u306B\u6295\u7A3F", async () => {
      const file = this.app.workspace.getActiveFile();
      if (file && file.extension === "md") {
        await this.publishCurrentFile(file);
      } else {
        new import_obsidian.Notice("Markdown \u30D5\u30A1\u30A4\u30EB\u3092\u958B\u3044\u3066\u304F\u3060\u3055\u3044");
      }
    });
    this.addSettingTab(new XPublisherSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    var _a;
    await this.saveData(this.settings);
    (_a = this.xClient) == null ? void 0 : _a.setServerUrl(this.settings.serverUrl);
  }
  async publishCurrentFile(file, skipConfirmation = false) {
    try {
      const parsedNote = await parseNote(this.app, file);
      if (skipConfirmation) {
        await this.doPublish(parsedNote, file);
      } else {
        new PublishConfirmModal(this.app, parsedNote, () => this.doPublish(parsedNote, file), () => {
        }).open();
      }
    } catch (error) {
      this.handleError(error);
    }
  }
  async doPublish(parsedNote, file) {
    var _a;
    const loadingNotice = new import_obsidian.Notice("X Article \u306B\u6295\u7A3F\u4E2D...", 0);
    try {
      await updateFrontmatter(this.app, file, { x_status: "publishing", x_error: "" });
    } catch (e) {
    }
    try {
      const validImages = parsedNote.images.filter((img) => img.exists).map((img) => ({ fileName: img.fileName, absolutePath: img.absolutePath }));
      const result = await this.xClient.publish({
        title: parsedNote.title,
        markdown: parsedNote.body,
        images: validImages,
        headless: this.settings.headlessMode
      });
      loadingNotice.hide();
      if (result.success) {
        const updates = { x_status: "published", x_error: "" };
        if (result.articleUrl)
          updates.x_url = result.articleUrl;
        const cache = this.app.metadataCache.getFileCache(file);
        if (!((_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.x_publish_date)) {
          updates.x_publish_date = getTodayDate();
        }
        try {
          await updateFrontmatter(this.app, file, updates);
        } catch (e) {
        }
        if (this.settings.showNotification) {
          new import_obsidian.Notice(`\u6295\u7A3F\u5B8C\u4E86: "${parsedNote.title}"`);
        }
        if (this.settings.openAfterPublish && result.articleUrl) {
          window.open(result.articleUrl, "_blank");
        } else if (this.settings.openAfterPublish) {
          window.open("https://x.com/i/articles", "_blank");
        }
      } else {
        throw new Error(result.error || "Unknown error");
      }
    } catch (error) {
      loadingNotice.hide();
      const errorMessage = this.getShortErrorMessage(error);
      try {
        await updateFrontmatter(this.app, file, { x_status: "review", x_error: errorMessage });
      } catch (e) {
      }
      this.handleError(error);
    }
  }
  getShortErrorMessage(error) {
    const message = error.message || String(error);
    if (message.includes("ECONNREFUSED") || message.includes("fetch"))
      return "\u30B5\u30FC\u30D0\u30FC\u63A5\u7D9A\u5931\u6557";
    if (message.includes("timeout"))
      return "\u30BF\u30A4\u30E0\u30A2\u30A6\u30C8";
    if (message.includes("\u672A\u9023\u643A") || message.includes("cookies"))
      return "\u8A8D\u8A3C\u30A8\u30E9\u30FC";
    if (message.length > 50)
      return message.substring(0, 47) + "...";
    return message;
  }
  handleError(error) {
    const message = error.message || String(error);
    let userMessage = "X Article \u3078\u306E\u6295\u7A3F\u306B\u5931\u6557\u3057\u307E\u3057\u305F";
    if (message.includes("ECONNREFUSED") || message.includes("fetch")) {
      userMessage = `\u30B5\u30FC\u30D0\u30FC\u306B\u63A5\u7D9A\u3067\u304D\u307E\u305B\u3093\u3002\u30BF\u30FC\u30DF\u30CA\u30EB\u3067 npm run server \u3092\u5B9F\u884C\u3057\u3001\u30D7\u30E9\u30B0\u30A4\u30F3\u8A2D\u5B9A\u3092\u78BA\u8A8D\u3057\u3066\u304F\u3060\u3055\u3044\u3002`;
    } else if (message.includes("\u672A\u9023\u643A") || message.includes("cookies")) {
      userMessage = "X \u30A2\u30AB\u30A6\u30F3\u30C8\u304C\u9023\u643A\u3055\u308C\u3066\u3044\u307E\u305B\u3093\u3002\u30D7\u30E9\u30B0\u30A4\u30F3\u8A2D\u5B9A\u304B\u3089\u300CX \u30A2\u30AB\u30A6\u30F3\u30C8\u3092\u9023\u643A\u300D\u3092\u5B9F\u884C\u3057\u3066\u304F\u3060\u3055\u3044\u3002";
    } else if (message.includes("timeout")) {
      userMessage = "\u30BF\u30A4\u30E0\u30A2\u30A6\u30C8\u3057\u307E\u3057\u305F\u3002\u3082\u3046\u4E00\u5EA6\u304A\u8A66\u3057\u304F\u3060\u3055\u3044\u3002";
    } else {
      userMessage = `\u30A8\u30E9\u30FC: ${message}`;
    }
    new import_obsidian.Notice(userMessage, 1e4);
  }
};
